name: Build and deploy

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'test-workflow-branch'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@prodyna-eudel'
      - run: npm ci --legacy-peer-deps
      - run: npm link --legacy-peer-deps @angular/cli
      - run: ng build angular-google-charts --configuration production
      - working-directory: ./dist/angular-google-charts
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm version prerelease --preid=$(git rev-parse HEAD) -git-tag-version=false
          npm publish
